name: Resume Builder Pipeline

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing Modules
        run: npm install --legacy-peer-deps

      - name: 🔨 Build Angular app
        run: npm run ghbuild
      
      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/resumebuilder --no-silent --repo=https://x-access-token:${{ secrets.CICD_TOKEN }}@github.com/krishnasonune/resumebuilder.git --name="GitHub Actions" --email="actions@github.com" --branch=gh-pages
